FreeBSD_task:
  matrix:
    env:
      SSL: openssl
    env:
      SSL: libressl
    env:
      SSL: libressl-devel
    env:
      # base openssl
      SSL:
  matrix:
    freebsd_instance:
      image_family: freebsd-12-1
  prepare_script:
    - pkg install -y cmake git $SSL
    - git submodule update --init --recursive
  configure_script:
    - ./configure
  build_script:
    - make -j $(sysctl -n hw.ncpu || echo 4) -C build
  test_script:
    - ldd build/vpnserver
    - .ci/memory-leak-test.sh
    - .ci/vpntools-check.sh
