//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.5472
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------
// Comments: Tetsuo Sugiyama, Ph.D.
// 
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// version 2 as published by the Free Software Foundation.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License version 2
// along with this program; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
// IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
// CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
// TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
// SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
// 
// THE LICENSE AGREEMENT IS ATTACHED ON THE SOURCE-CODE PACKAGE
// AS "LICENSE.TXT" FILE. READ THE TEXT FILE IN ADVANCE TO USE THE SOFTWARE.
// 
// 
// THIS SOFTWARE IS DEVELOPED IN JAPAN, AND DISTRIBUTED FROM JAPAN,
// UNDER JAPANESE LAWS. YOU MUST AGREE IN ADVANCE TO USE, COPY, MODIFY,
// MERGE, PUBLISH, DISTRIBUTE, SUBLICENSE, AND/OR SELL COPIES OF THIS
// SOFTWARE, THAT ANY JURIDICAL DISPUTES WHICH ARE CONCERNED TO THIS
// SOFTWARE OR ITS CONTENTS, AGAINST US (SOFTETHER PROJECT, SOFTETHER
// CORPORATION, DAIYUU NOBORI OR OTHER SUPPLIERS), OR ANY JURIDICAL
// DISPUTES AGAINST US WHICH ARE CAUSED BY ANY KIND OF USING, COPYING,
// MODIFYING, MERGING, PUBLISHING, DISTRIBUTING, SUBLICENSING, AND/OR
// SELLING COPIES OF THIS SOFTWARE SHALL BE REGARDED AS BE CONSTRUED AND
// CONTROLLED BY JAPANESE LAWS, AND YOU MUST FURTHER CONSENT TO
// EXCLUSIVE JURISDICTION AND VENUE IN THE COURTS SITTING IN TOKYO,
// JAPAN. YOU MUST WAIVE ALL DEFENSES OF LACK OF PERSONAL JURISDICTION
// AND FORUM NON CONVENIENS. PROCESS MAY BE SERVED ON EITHER PARTY IN
// THE MANNER AUTHORIZED BY APPLICABLE LAW OR COURT RULE.
// 
// USE ONLY IN JAPAN. DO NOT USE THIS SOFTWARE IN ANOTHER COUNTRY UNLESS
// YOU HAVE A CONFIRMATION THAT THIS SOFTWARE DOES NOT VIOLATE ANY
// CRIMINAL LAWS OR CIVIL RIGHTS IN THAT PARTICULAR COUNTRY. USING THIS
// SOFTWARE IN OTHER COUNTRIES IS COMPLETELY AT YOUR OWN RISK. THE
// SOFTETHER VPN PROJECT HAS DEVELOPED AND DISTRIBUTED THIS SOFTWARE TO
// COMPLY ONLY WITH THE JAPANESE LAWS AND EXISTING CIVIL RIGHTS INCLUDING
// PATENTS WHICH ARE SUBJECTS APPLY IN JAPAN. OTHER COUNTRIES' LAWS OR
// CIVIL RIGHTS ARE NONE OF OUR CONCERNS NOR RESPONSIBILITIES. WE HAVE
// NEVER INVESTIGATED ANY CRIMINAL REGULATIONS, CIVIL LAWS OR
// INTELLECTUAL PROPERTY RIGHTS INCLUDING PATENTS IN ANY OF OTHER 200+
// COUNTRIES AND TERRITORIES. BY NATURE, THERE ARE 200+ REGIONS IN THE
// WORLD, WITH DIFFERENT LAWS. IT IS IMPOSSIBLE TO VERIFY EVERY
// COUNTRIES' LAWS, REGULATIONS AND CIVIL RIGHTS TO MAKE THE SOFTWARE
// COMPLY WITH ALL COUNTRIES' LAWS BY THE PROJECT. EVEN IF YOU WILL BE
// SUED BY A PRIVATE ENTITY OR BE DAMAGED BY A PUBLIC SERVANT IN YOUR
// COUNTRY, THE DEVELOPERS OF THIS SOFTWARE WILL NEVER BE LIABLE TO
// RECOVER OR COMPENSATE SUCH DAMAGES, CRIMINAL OR CIVIL
// RESPONSIBILITIES. NOTE THAT THIS LINE IS NOT LICENSE RESTRICTION BUT
// JUST A STATEMENT FOR WARNING AND DISCLAIMER.
// 
// 
// SOURCE CODE CONTRIBUTION
// ------------------------
// 
// Your contribution to SoftEther VPN Project is much appreciated.
// Please send patches to us through GitHub.
// Read the SoftEther VPN Patch Acceptance Policy in advance:
// http://www.softether.org/5-download/src/9.patch
// 
// 
// DEAR SECURITY EXPERTS
// ---------------------
// 
// If you find a bug or a security vulnerability please kindly inform us
// about the problem immediately so that we can fix the security problem
// to protect a lot of users around the world as soon as possible.
// 
// Our e-mail address for security reports is:
// softether-vpn-security [at] softether.org
// 
// Please note that the above e-mail address is not a technical support
// inquiry address. If you need technical assistance, please visit
// http://www.softether.org/ and ask your question on the users forum.
// 
// Thank you for your cooperation.
// 
// 
// NO MEMORY OR RESOURCE LEAKS
// ---------------------------
// 
// The memory-leaks and resource-leaks verification under the stress
// test has been passed before release this source code.


namespace BuildUtil.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BuildUtil.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   [j]追加[e]Add[/] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CDF_BUTTON_ADD {
            get {
                return ResourceManager.GetString("CDF_BUTTON_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///     [j]キャンセル[e]Cancel[/]   に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CDF_BUTTON_CANCEL {
            get {
                return ResourceManager.GetString("CDF_BUTTON_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///      [j]完  了[e]Complete[/]    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CDF_BUTTON_COMPLETE {
            get {
                return ResourceManager.GetString("CDF_BUTTON_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [j]削除[e]Delete[/] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CDF_BUTTON_DELETE {
            get {
                return ResourceManager.GetString("CDF_BUTTON_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [j]編集[e]Edit[/] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CDF_BUTTON_EDIT {
            get {
                return ResourceManager.GetString("CDF_BUTTON_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///     [j]修正する[e]Modify[/]   に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CDF_BUTTON_MODIFY {
            get {
                return ResourceManager.GetString("CDF_BUTTON_MODIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///      O  K    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CDF_BUTTON_OK {
            get {
                return ResourceManager.GetString("CDF_BUTTON_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///     [j]処理中[e]Wait[/]... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CDF_BUTTON_SENDING {
            get {
                return ResourceManager.GetString("CDF_BUTTON_SENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   　[j]最近の候補[e]Recent Candidates[/]:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CDF_CANDIDATES {
            get {
                return ResourceManager.GetString("CDF_CANDIDATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [j]日付が入力されていません。[e]Date field is empty.[/] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CDF_DATE_EMPTY {
            get {
                return ResourceManager.GetString("CDF_DATE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [j]{0} 以前の日付を指定してください。[e]Please specify a date before {0}.[/] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CDF_DATE_MAX {
            get {
                return ResourceManager.GetString("CDF_DATE_MAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [j]{0} 以降の日付を指定してください。[e]Please specift a date since {0}.[/] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CDF_DATE_MIN {
            get {
                return ResourceManager.GetString("CDF_DATE_MIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [j]日付として認識できない文字列が入力されています。[e]Can&apos;t recognize as a valid date.[/] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CDF_DATE_NOTDATE {
            get {
                return ResourceManager.GetString("CDF_DATE_NOTDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [j]全件表示 ({0} 件)[e]Total ({0} entities)[/] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CDF_DL_ALL {
            get {
                return ResourceManager.GetString("CDF_DL_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [j]ダウンロード[e]Download[/] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CDF_DOWNLOAD {
            get {
                return ResourceManager.GetString("CDF_DOWNLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [j]日時が入力されていません。[e]Date and Time are empty.[/] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CDF_DT_EMPTY {
            get {
                return ResourceManager.GetString("CDF_DT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [j]{0} 以前の日時を指定してください。[e]Please specify a date and a time before {0}.[/] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CDF_DT_MAX {
            get {
                return ResourceManager.GetString("CDF_DT_MAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [j]{0} 以降の日時を指定してください。[e]Please specify a date and a time since {0}.[/] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CDF_DT_MIN {
            get {
                return ResourceManager.GetString("CDF_DT_MIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [j]日時として認識できない文字列が入力されています。[e]Can&apos;t recognize as a valid date and a time.[/] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CDF_DT_NOTDT {
            get {
                return ResourceManager.GetString("CDF_DT_NOTDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [j]記入例[e]Example[/] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CDF_EXAMPLE {
            get {
                return ResourceManager.GetString("CDF_EXAMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [j]ＭＳ ゴシック[e]MS Gothic[/] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CDF_GOTHIC {
            get {
                return ResourceManager.GetString("CDF_GOTHIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [j]データ構造のフィールド数が 1 でありません。[e]The number of fields of data structures is not one.[/] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CDF_GRID_ERROR_1 {
            get {
                return ResourceManager.GetString("CDF_GRID_ERROR_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [j]データ構造がリストでありません。[e]The data structure is not a list.[/] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CDF_GRID_ERROR_2 {
            get {
                return ResourceManager.GetString("CDF_GRID_ERROR_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [j]数値は {0} 以下を指定してください。[e]The value must be {0} or less.[/] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CDF_INT_MAX {
            get {
                return ResourceManager.GetString("CDF_INT_MAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [j]数値は {0} 以上を指定してください。[e]The value must be {0} or more.[/] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CDF_INT_MIN {
            get {
                return ResourceManager.GetString("CDF_INT_MIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [j]整数以外の文字が入力されています。[e]The value can&apos;t be recognized as an integer.[/] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CDF_INT_NOT_NUMBER_CHAR {
            get {
                return ResourceManager.GetString("CDF_INT_NOT_NUMBER_CHAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [j]数値が正しく入力されていません。[e]The value can&apos;t be recognized as a formal figure.[/] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CDF_INT_NOTINTEGER {
            get {
                return ResourceManager.GetString("CDF_INT_NOTINTEGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [j]データ &quot;{0}&quot; はこのリストでは不正です。[e]The data &quot;{0}&quot; is invalid at this list.[/] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CDF_INVALID {
            get {
                return ResourceManager.GetString("CDF_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [j]メールアドレスが不正です。[e]The mail address is invalid.[/] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CDF_INVALID_EMAIL {
            get {
                return ResourceManager.GetString("CDF_INVALID_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [j]【 {0} 個目の項目 (合計 {1} 個中) - {2} 】[e]Item of piece {0} (Total: {1} entities) - {2}[/] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CDF_LIST_FORMAT {
            get {
                return ResourceManager.GetString("CDF_LIST_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CdfClass 属性が正しく指定されていないクラス %s が指定されました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CDF_NO_CDFCLASS {
            get {
                return ResourceManager.GetString("CDF_NO_CDFCLASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %s 項目に %s 属性が 1 つ指定されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CDF_NO_SINGLE_ATT {
            get {
                return ResourceManager.GetString("CDF_NO_SINGLE_ATT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %s 項目のジェネリック型が 1 つ指定されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CDF_NO_SINGLE_GENERIC_TYPE {
            get {
                return ResourceManager.GetString("CDF_NO_SINGLE_GENERIC_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [j]項目なし[e]No Entities[/] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CDF_NOITEM {
            get {
                return ResourceManager.GetString("CDF_NOITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [j]項目が選択されていません。[e]You have to select an entity.[/] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CDF_NOT_SELECTED {
            get {
                return ResourceManager.GetString("CDF_NOT_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [j]正しく選択されていません。[e]You have to select correctly.[/] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CDF_NOT_SELECTED_2 {
            get {
                return ResourceManager.GetString("CDF_NOT_SELECTED_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [j]ページ {0}[e]Page {0}[/] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CDF_PAGING_FORMAT_1 {
            get {
                return ResourceManager.GetString("CDF_PAGING_FORMAT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [j]最新 {0} 件[e]Latest: {0} entities[/] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CDF_PAGING_FORMAT_2 {
            get {
                return ResourceManager.GetString("CDF_PAGING_FORMAT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [j] ({2}: {0} ～ {1})[e] ({2}: {0} - {1})[/] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CDF_PAGING_HELPSTR_FORMAT {
            get {
                return ResourceManager.GetString("CDF_PAGING_HELPSTR_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [j]▼選択してください▼[e]- Please Select Here -[/] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CDF_PLEASE_SELECT {
            get {
                return ResourceManager.GetString("CDF_PLEASE_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [j]削除[e]Delete[/] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CDF_REMOVE {
            get {
                return ResourceManager.GetString("CDF_REMOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [j]この項目を削除します。よろしいですか？[e]Do you want to delete this entity?[/] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CDF_REMOVEMSG {
            get {
                return ResourceManager.GetString("CDF_REMOVEMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [j]項目が 1 件も見つかりませんでした。[e]No entity is found.[/] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CDF_ROW_EMPTY {
            get {
                return ResourceManager.GetString("CDF_ROW_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [j]▽選択可能[e]- Selectable -[/] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CDF_SELECTABLE {
            get {
                return ResourceManager.GetString("CDF_SELECTABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [j]▲「{0}」でソート[e]Sort by &quot;{0}&quot; Ascending[/] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CDF_SORT_1 {
            get {
                return ResourceManager.GetString("CDF_SORT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [j]▼「{0}」で逆ソート[e]Sort by &quot;{0}&quot; Descending[/] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CDF_SORT_2 {
            get {
                return ResourceManager.GetString("CDF_SORT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [j]▲標準のソート[e]Standard Ascending Sort[/] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CDF_SORT_DEF1 {
            get {
                return ResourceManager.GetString("CDF_SORT_DEF1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [j]▼標準の逆ソート[e]Standard Descending Sort[/] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CDF_SORT_DEF2 {
            get {
                return ResourceManager.GetString("CDF_SORT_DEF2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [j]使用できない文字が含まれています。[e]There are some invalid characters which can&apos;t be used.[/] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CDF_STRING_INVALIDCHAR {
            get {
                return ResourceManager.GetString("CDF_STRING_INVALIDCHAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [j]文字数は {0} 以下にする必要があります。[e]The number of characters must be {0} or less.[/] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CDF_STRING_MAX {
            get {
                return ResourceManager.GetString("CDF_STRING_MAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [j]文字を {0} 文字以上入力する必要があります。[e]The number of characters must be {0} or more.[/] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CDF_STRING_MIN {
            get {
                return ResourceManager.GetString("CDF_STRING_MIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [j]改行文字を含めることはできません。[e]There must not be any New-Line characters in the string.[/] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CDF_STRING_NOLINE {
            get {
                return ResourceManager.GetString("CDF_STRING_NOLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [j]表示不可能な文字コードが含まれています。[e]There must not be any Non-Printable characters in the string.[/] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CDF_STRING_NONPRINTABLE {
            get {
                return ResourceManager.GetString("CDF_STRING_NONPRINTABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [j]入力いただいた内容を確認のため表示しています。内容をよくご確認ください。&lt;BR&gt;この内容で確定する場合は [OK] ボタンを、修正する場合は [修正する] ボタンをクリックしてください。[e]Please confirm the printed data which you input. Please read it carefully.&lt;BR&gt;If you want to commit with this data, click the &quot;OK&quot; button. Otherwise, click the &quot;Modify&quot; button.[/] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CDF_TEXT_CONFIRM {
            get {
                return ResourceManager.GetString("CDF_TEXT_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [j]エラーが発生しました。内容を見直してください。修正する場合は [修正する] ボタンをクリックしてください。[e]An error has been occurred. Please confirm the fields. To modify it, click the &quot;Modify&quot; button.[/] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CDF_TEXT_CONFIRM_ERROR {
            get {
                return ResourceManager.GetString("CDF_TEXT_CONFIRM_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [j]入力が完了したら [OK] ボタンを、入力をキャンセルするには [キャンセル] ボタンをクリックしてください。[e]Please click the &quot;OK&quot; button after you complete filling all nessesary fields. To cancel inputting, click the &quot;Cancel&quot; button.[/] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CDF_TEXT_OK {
            get {
                return ResourceManager.GetString("CDF_TEXT_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [j]時刻が入力されていません。[e]Time is empty.[/] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CDF_TIME_EMPTY {
            get {
                return ResourceManager.GetString("CDF_TIME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [j]{0} 以前の時刻を指定してください。[e]Please specify a time before {0}.[/] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CDF_TIME_MAX {
            get {
                return ResourceManager.GetString("CDF_TIME_MAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [j]{0} 以降の時刻を指定してください。[e]Please specify a time after {0}.[/] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CDF_TIME_MIN {
            get {
                return ResourceManager.GetString("CDF_TIME_MIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [j]時刻として認識できない文字列が入力されています。[e]Can&apos;t recognize as a valid time.[/] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CDF_TIME_NOTTIME {
            get {
                return ResourceManager.GetString("CDF_TIME_NOTTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [j]フィールド %s の型 %s がサポートされていません。[e]In the field &quot;%s&quot;, the type &quot;%s&quot; is not supported.[/] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CDF_UNSUPPORTED {
            get {
                return ResourceManager.GetString("CDF_UNSUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Item に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMD_CT_STD_COLUMN_1 {
            get {
                return ResourceManager.GetString("CMD_CT_STD_COLUMN_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMD_CT_STD_COLUMN_2 {
            get {
                return ResourceManager.GetString("CMD_CT_STD_COLUMN_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The date and time specification is invalid. \nThe date and time must be in the same format as &quot;2005/10/08 19:30:00&quot; where 6 integers are specified, representing year/month/day hour:minute:second separated by forward slashes, a space and then colons. Specify 4 digits for the year. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMD_EVAL_DATE_TIME_FAILED {
            get {
                return ResourceManager.GetString("CMD_EVAL_DATE_TIME_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You must specify an integer that is not less than 1. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMD_EVAL_INT {
            get {
                return ResourceManager.GetString("CMD_EVAL_INT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You must specify an integer in the range from %u to %u for the value. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMD_EVAL_MIN_MAX {
            get {
                return ResourceManager.GetString("CMD_EVAL_MIN_MAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You cannot make a blank specification. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMD_EVAL_NOT_EMPTY {
            get {
                return ResourceManager.GetString("CMD_EVAL_NOT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Port number is invalid. Specify a port number that is within the range of 1 to 65535. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMD_EVAL_PORT {
            get {
                return ResourceManager.GetString("CMD_EVAL_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The string contains unusable characters. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMD_EVAL_SAFE {
            get {
                return ResourceManager.GetString("CMD_EVAL_SAFE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %S command - %s に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMD_EXEC_MSG_NAME {
            get {
                return ResourceManager.GetString("CMD_EXEC_MSG_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file name is not specified. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMD_FILE_NAME_EMPTY {
            get {
                return ResourceManager.GetString("CMD_FILE_NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot find specified file &quot;%s&quot;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMD_FILE_NOT_FOUND {
            get {
                return ResourceManager.GetString("CMD_FILE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can use the following %u commands: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMD_HELP_1 {
            get {
                return ResourceManager.GetString("CMD_HELP_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To reference the usage for each command, input &quot;command name /?&quot; to view a help. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMD_HELP_2 {
            get {
                return ResourceManager.GetString("CMD_HELP_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parameters: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMD_HELP_ARGS {
            get {
                return ResourceManager.GetString("CMD_HELP_ARGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Purpose: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMD_HELP_DESCRIPTION {
            get {
                return ResourceManager.GetString("CMD_HELP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Description: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMD_HELP_HELP {
            get {
                return ResourceManager.GetString("CMD_HELP_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Help for command &quot;%S&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMD_HELP_TITLE {
            get {
                return ResourceManager.GetString("CMD_HELP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Usage: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMD_HELP_USAGE {
            get {
                return ResourceManager.GetString("CMD_HELP_USAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;IP アドレス/サブネットマスク&quot; の形式で指定してください。
        ///IP アドレスは 192.168.0.1 のように 10 進数をドットで区切って指定します。サブネットマスクは 255.255.255.0 のように 10 進数をドットで区切って指定するか、24 のように先頭からのビット長を 10 進数で指定できます。
        ///単一のホストを指定するには、サブネットマスクを 255.255.255.255 または 32 として指定します。
        ///(例)
        /// 192.168.0.1/24
        /// 192.168.0.1/255.255.255.0
        ///192.168.0.5/255.255.255.255
        ///
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMD_PARSE_IP_SUBNET_ERROR_1 {
            get {
                return ResourceManager.GetString("CMD_PARSE_IP_SUBNET_ERROR_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定された IP アドレスはネットワークアドレスではありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMD_PARSE_IP_SUBNET_ERROR_2 {
            get {
                return ResourceManager.GetString("CMD_PARSE_IP_SUBNET_ERROR_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter a value:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMD_PROMPT {
            get {
                return ResourceManager.GetString("CMD_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input the port number:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMD_PROPMT_PORT {
            get {
                return ResourceManager.GetString("CMD_PROPMT_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no description for this command. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMD_UNKNOWM {
            get {
                return ResourceManager.GetString("CMD_UNKNOWM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no command execution example. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMD_UNKNOWN_ARGS {
            get {
                return ResourceManager.GetString("CMD_UNKNOWN_ARGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no detailed description for this command. If you would like to know more detail about this command, please refer to the manual or online documentation. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMD_UNKNOWN_HELP {
            get {
                return ResourceManager.GetString("CMD_UNKNOWN_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no description for this parameter. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMD_UNKNOWN_PARAM {
            get {
                return ResourceManager.GetString("CMD_UNKNOWN_PARAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;%S&quot;: The command-name is ambiguous. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CON_AMBIGIOUS_CMD {
            get {
                return ResourceManager.GetString("CON_AMBIGIOUS_CMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The specified command name matches the following multiple commands. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CON_AMBIGIOUS_CMD_1 {
            get {
                return ResourceManager.GetString("CON_AMBIGIOUS_CMD_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please re-specify the command name more strictly. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CON_AMBIGIOUS_CMD_2 {
            get {
                return ResourceManager.GetString("CON_AMBIGIOUS_CMD_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;%S&quot;: The parameter name is ambiguous. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CON_AMBIGIOUS_PARAM {
            get {
                return ResourceManager.GetString("CON_AMBIGIOUS_PARAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The specified parameter name matches with the following parameters that can be specified as a parameter of command &quot;%S&quot;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CON_AMBIGIOUS_PARAM_1 {
            get {
                return ResourceManager.GetString("CON_AMBIGIOUS_PARAM_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please re-specify the parameter name more strictly. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CON_AMBIGIOUS_PARAM_2 {
            get {
                return ResourceManager.GetString("CON_AMBIGIOUS_PARAM_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error: Unable to open the specified input file &quot;%s&quot;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CON_INFILE_ERROR {
            get {
                return ResourceManager.GetString("CON_INFILE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The commands written in the file &quot;%s&quot; will be used instead of input from keyboard. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CON_INFILE_START {
            get {
                return ResourceManager.GetString("CON_INFILE_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The parameter &quot;/%S&quot; has been specified. It is not possible to specify this parameter when using the command &quot;%S&quot;. Input &quot;%S /HELP&quot; to see the list of what parameters can be used. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CON_INVALID_PARAM {
            get {
                return ResourceManager.GetString("CON_INVALID_PARAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error: Unable to create the specified output file &quot;%s&quot;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CON_OUTFILE_ERROR {
            get {
                return ResourceManager.GetString("CON_OUTFILE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The message output to the console will be saved in the file &quot;%s&quot;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CON_OUTFILE_START {
            get {
                return ResourceManager.GetString("CON_OUTFILE_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;%S&quot;: Command not found. You can use the HELP command to view a list of the available commands. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CON_UNKNOWN_CMD {
            get {
                return ResourceManager.GetString("CON_UNKNOWN_CMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [EOF] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CON_USER_CANCEL {
            get {
                return ResourceManager.GetString("CON_USER_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The command was canceled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CON_USER_CANCELED {
            get {
                return ResourceManager.GetString("CON_USER_CANCELED", resourceCulture);
            }
        }
    }
}

// Developed by SoftEther VPN Project at University of Tsukuba in Japan.
// Department of Computer Science has dozens of overly-enthusiastic geeks.
// Join us: http://www.tsukuba.ac.jp/english/admission/
