#!/bin/sh
#
# vpnserver	This shell script takes care of starting and stopping
#		SoftEther VPN server.
#
# chkconfig:   - 99 1
# description: SoftEther VPN server.
#

### BEGIN INIT INFO
# Provides: vpnserver
# Required-Start: $local_fs $network
# Required-Stop: $local_fs $network
# Short-Description: start and stop SoftEther VPN server.
# Description: SoftEther VPN server.
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

exec="/usr/vpnserver/vpnserver"
prog="vpnserver"
#config="<path to major config file>"

#[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog

pidfile=/usr/vpnserver/.pid_3E649A678269D4A01B73BF9E3388D075
lockfile=/var/lock/subsys/$prog

start() {
	[ -x $exec ] || exit 5
#	[ -f $config ] || exit 6
	echo -n $"Starting $prog: "
	$exec start
	retval=$?
	echo
	[ $retval -eq 0 ] && touch $lockfile
	return $retval
}

stop() {
	echo -n $"Stopping $prog: "
	/usr/bin/timeout 60 $exec stop || /usr/bin/killall -q -9 $prog
	retval=$?
	echo
	[ $retval -eq 0 ] && rm -f $lockfile
	return $retval
}

restart() {
	stop
	start
}

reload() {
	restart
}

force_reload() {
	restart
}

rh_status() {
	status -p $pidfile $prog
}

rh_status_q() {
	rh_status >/dev/null 2>&1
}


case "$1" in
	start)
		rh_status_q && exit 0
		$1
		;;
	stop)
		rh_status_q || exit 0
		$1
		;;
	restart)
		$1
		;;
	reload)
		rh_status_q || exit 7
		$1
		;;
	force-reload)
		force_reload
		;;
	status)
		rh_status
		;;
	condrestart|try-restart)
		rh_status_q || exit 0
		restart
		;;
	*)
		echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
		exit 2
esac
exit $?
