name: LibreSSL

on: [push, pull_request]

permissions:
  contents: read

jobs:
  libressl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - name: Install dependencies
        run: sudo apt update && sudo apt-get -y install wget pkg-config cmake gcc g++ ninja-build libncurses5-dev libreadline-dev libsodium-dev make zlib1g-dev liblz4-dev libnl-genl-3-dev

      - name: Install LibreSSL
        run: sudo LIBRESSL_VERSION="4.3.2" OPENSSL_INSTALL_DIR="/usr/local" .ci/build-libressl.sh

      - name: Build
        run: |
          mkdir build
          cd build
          cmake -G "Ninja" -DOPENSSL_ROOT_DIR="/usr/local"  -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
          cmake --build .

      - name: Test
        run: |
          .ci/memory-leak-test.sh
          .ci/vpntools-check.sh
