name: Alpine/musl

on:
  push:
  pull_request:

jobs:
  musl:
    name: gcc
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:

      - name: Install dependencies
        run: |
          apk add binutils --no-cache build-base readline-dev openssl-dev ncurses-dev git cmake zlib-dev libsodium-dev gnu-libiconv 

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Configure
        run: |
          ./configure

      - name: make 
        run: |
          make -C build