name: OpenSUSE

on: [push]

jobs:
  tumbletweed:
      name: gcc
      runs-on: ubuntu-latest
      container:
        image: opensuse/tumbleweed
      steps:
        - name: Install prerequisites
          run: |
            zypper refresh
            zypper --non-interactive install libopenssl-devel cmake gcc gcc-c++ tar gzip git ncurses-devel zlib-devel readline-devel
        - uses: actions/checkout@master
          with:
            submodules: true
        - name: Build
          run: |
            ./configure
            make -j $(nproc || sysctl -n hw.ncpu || echo 4) -C build
            ldd build/vpnserver

