name: STB Check

on:
  push:
  pull_request:

jobs:
  check:
      name: Check
      runs-on: ubuntu-latest
      steps:

        - name: Checkout
          uses: actions/checkout@v4
          with:
            submodules: true

        - name: Check
          run: |
            cd developer_tools/stbchecker
            dotnet run ../../src/bin/hamcore